#ifndef __DATA_STRUCTURES__
#define _DATA_STRUCTURES_



#define NOT_ENOUGH_KEYPOINTS_FAIL "NOT_ENOUGH_KEYPOINTS_FAIL"
#define SEGMENTATION_OCR_FAIL "SEGMENTATION_OCR_FAIL"

#endif // !__DATA_STRUCTURES__


